export type FunctionDefinition = {
  id: string;
  name: string;
  category: 'observe' | 'research' | 'enrich' | 'validate' | 'opportunity' | 'draft' | 'jobs' | 'learning' | 'system';
  description: string;
  entityScope: 'account' | 'person' | 'signal' | 'pattern' | 'queue' | 'system';
  inputs: string[];
  outputType: string;
  canBatch: boolean;
  requiresConfirmation: boolean;
  jobType: string | null;
  uiPlacement: string[];
  explainabilitySupported: boolean;
  producesEntityMutations: boolean;
  producesActions: boolean;
  producesDrafts: boolean;
  actionCommand?: string | null;
};

export const functionRegistry: FunctionDefinition[] = [
  {
    id: 'scan-account',
    name: 'Scan Account',
    category: 'observe',
    description: 'Run a fresh account scan to collect visible site, technology, and structural signals.',
    entityScope: 'account',
    inputs: ['domain'],
    outputType: 'scan report',
    canBatch: true,
    requiresConfirmation: false,
    jobType: 'research.run',
    uiPlacement: ['command-bar', 'account-detail', 'capabilities'],
    explainabilitySupported: true,
    producesEntityMutations: true,
    producesActions: false,
    producesDrafts: false,
    actionCommand: 'queue research {domain}',
  },
  {
    id: 'refresh-stale-entities',
    name: 'Refresh Stale Entities',
    category: 'enrich',
    description: 'Queue refresh work for stale or incomplete entities so downstream ranking stops using expired assumptions.',
    entityScope: 'system',
    inputs: ['filter or default stale set'],
    outputType: 'enrichment jobs',
    canBatch: true,
    requiresConfirmation: true,
    jobType: 'refresh_stale_entities',
    uiPlacement: ['system-lab', 'copilot', 'capabilities'],
    explainabilitySupported: true,
    producesEntityMutations: true,
    producesActions: false,
    producesDrafts: false,
    actionCommand: 'refresh stale entities',
  },
  {
    id: 'recalculate-opportunity-scores',
    name: 'Recalculate Opportunity Scores',
    category: 'opportunity',
    description: 'Re-rank current action candidates using the latest signals, policy versions, and confidence decomposition.',
    entityScope: 'queue',
    inputs: ['daily limit', 'max per account'],
    outputType: 'action queue',
    canBatch: true,
    requiresConfirmation: true,
    jobType: 'recompute_drift_metrics',
    uiPlacement: ['actions', 'system-lab', 'capabilities'],
    explainabilitySupported: true,
    producesEntityMutations: true,
    producesActions: true,
    producesDrafts: false,
    actionCommand: 'recalculate scores',
  },
  {
    id: 'generate-sdr-actions',
    name: 'Generate SDR Actions',
    category: 'opportunity',
    description: 'Produce the current best-ranked SDR actions from available evidence, patterns, and entity state.',
    entityScope: 'queue',
    inputs: ['accounts/signals/candidates'],
    outputType: 'top action queue',
    canBatch: true,
    requiresConfirmation: false,
    jobType: 'action-candidate.generate',
    uiPlacement: ['overview', 'actions', 'copilot', 'capabilities'],
    explainabilitySupported: true,
    producesEntityMutations: true,
    producesActions: true,
    producesDrafts: false,
    actionCommand: 'generate sdr actions',
  },
  {
    id: 'generate-email-draft',
    name: 'Generate Email Draft',
    category: 'draft',
    description: 'Generate an evidence-backed email draft using the active draft and strategy policies.',
    entityScope: 'account',
    inputs: ['action candidate', 'account context', 'person context'],
    outputType: 'gmail draft',
    canBatch: true,
    requiresConfirmation: false,
    jobType: null,
    uiPlacement: ['account-detail', 'actions', 'capabilities'],
    explainabilitySupported: true,
    producesEntityMutations: true,
    producesActions: false,
    producesDrafts: true,
    actionCommand: 'generate sdr actions',
  },
  {
    id: 'inspect-pattern',
    name: 'Inspect Pattern',
    category: 'validate',
    description: 'Explain why a pattern matches, how often it fires, and whether it should remain active.',
    entityScope: 'pattern',
    inputs: ['pattern id'],
    outputType: 'pattern explanation',
    canBatch: false,
    requiresConfirmation: false,
    jobType: null,
    uiPlacement: ['patterns', 'copilot', 'capabilities'],
    explainabilitySupported: true,
    producesEntityMutations: false,
    producesActions: false,
    producesDrafts: false,
    actionCommand: 'preview strategy',
  },
  {
    id: 'run-nightly-jobs',
    name: 'Run Nightly Jobs',
    category: 'jobs',
    description: 'Trigger the nightly intelligence pipeline including queue regeneration, drift metrics, and brief creation.',
    entityScope: 'system',
    inputs: ['optional date'],
    outputType: 'nightly run result',
    canBatch: false,
    requiresConfirmation: true,
    jobType: 'intelligence.nightly',
    uiPlacement: ['system-lab', 'jobs', 'capabilities'],
    explainabilitySupported: true,
    producesEntityMutations: true,
    producesActions: true,
    producesDrafts: false,
    actionCommand: 'run nightly jobs',
  },
  {
    id: 'run-scenario-suite',
    name: 'Run Scenario Regression Suite',
    category: 'system',
    description: 'Execute the scenario regression fixtures to detect ranking or anti-drift regressions.',
    entityScope: 'system',
    inputs: ['fixture set'],
    outputType: 'scenario regression report',
    canBatch: false,
    requiresConfirmation: true,
    jobType: 'run_scenario_regression_suite',
    uiPlacement: ['system-lab', 'capabilities'],
    explainabilitySupported: true,
    producesEntityMutations: false,
    producesActions: false,
    producesDrafts: false,
    actionCommand: 'queue anti drift maintenance',
  },
  {
    id: 'explain-score',
    name: 'Explain Score',
    category: 'validate',
    description: 'Break down score composition, strongest drivers, and confidence decomposition for a candidate.',
    entityScope: 'queue',
    inputs: ['action candidate id'],
    outputType: 'score explanation',
    canBatch: false,
    requiresConfirmation: false,
    jobType: null,
    uiPlacement: ['actions', 'account-detail', 'copilot', 'capabilities'],
    explainabilitySupported: true,
    producesEntityMutations: false,
    producesActions: false,
    producesDrafts: false,
    actionCommand: 'explain action {actionId}',
  },
  {
    id: 'queue-anti-drift-maintenance',
    name: 'Queue Anti-Drift Maintenance',
    category: 'learning',
    description: 'Queue anti-drift maintenance jobs for stale entity refresh, scenario regression, and reliability monitoring.',
    entityScope: 'system',
    inputs: ['include heavy jobs'],
    outputType: 'maintenance jobs',
    canBatch: false,
    requiresConfirmation: true,
    jobType: 'queueAntiDriftMaintenance',
    uiPlacement: ['system-lab', 'copilot', 'capabilities'],
    explainabilitySupported: true,
    producesEntityMutations: true,
    producesActions: false,
    producesDrafts: false,
    actionCommand: 'queue anti drift maintenance',
  },
  {
    id: 'run-autopilot',
    name: 'Run Autopilot',
    category: 'system',
    description: 'Run the bounded autonomous validation engine to replay scenarios, score confidence, and attempt safe repairs.',
    entityScope: 'system',
    inputs: ['runtime state', 'scenario history'],
    outputType: 'autopilot report',
    canBatch: false,
    requiresConfirmation: true,
    jobType: 'attempt_safe_repairs',
    uiPlacement: ['system-lab', 'capabilities', 'copilot'],
    explainabilitySupported: true,
    producesEntityMutations: true,
    producesActions: false,
    producesDrafts: false,
    actionCommand: 'run autopilot',
  },
];

export function groupedFunctionRegistry() {
  return functionRegistry.reduce<Record<string, FunctionDefinition[]>>((acc, item) => {
    acc[item.category] = acc[item.category] || [];
    acc[item.category].push(item);
    return acc;
  }, {});
}
