#!/bin/sh
# Reads .env and generates a TypeScript config file that gets compiled into the bundle.
# This bypasses Vite's import.meta.env which sanity build doesn't populate.

ENV_FILE=".env"
OUT_FILE="src/lib/build-env.generated.ts"

if [ ! -f "$ENV_FILE" ]; then
  echo "⚠️  No .env file found — generating empty build-env"
  cat > "$OUT_FILE" << 'EOF'
// Auto-generated by scripts/inject-env.sh — DO NOT EDIT
// Create .env and rebuild to populate these values
export const BUILD_ENV: Record<string, string> = {}
EOF
  exit 0
fi

echo "✓ Reading $ENV_FILE → $OUT_FILE"

# Read .env, skip comments and blank lines, extract key=value pairs
cat > "$OUT_FILE" << 'HEADER'
// Auto-generated by scripts/inject-env.sh — DO NOT EDIT
// Regenerated on every build from .env
export const BUILD_ENV: Record<string, string> = {
HEADER

grep -E '^VITE_' "$ENV_FILE" | while IFS='=' read -r key value; do
  # Remove surrounding quotes if present
  value=$(echo "$value" | sed "s/^['\"]//;s/['\"]$//")
  echo "  '$key': '$value'," >> "$OUT_FILE"
done

echo '}' >> "$OUT_FILE"

echo "✓ Build env generated with $(grep -c "VITE_" "$OUT_FILE") variables"
