#!/usr/bin/env node
/**
 * Inlines openapi.yaml into a JS module for the worker to serve at GET /openapi.yaml.
 * Run before deploy so the worker can serve the schema (fixes Custom GPT "unable to connect").
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const yamlPath = path.join(root, 'openapi.yaml');
const outDir = path.join(root, 'src', 'data');
const outPath = path.join(outDir, 'openapi-spec.js');

const yaml = fs.readFileSync(yamlPath, 'utf8');
// Escape for use inside a template literal: \ ` $
const escaped = yaml
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$/g, '\\$');

if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

fs.writeFileSync(
  outPath,
  `// Auto-generated by scripts/inline-openapi.js - do not edit\n` +
  `export default \`${escaped}\`;\n`,
  'utf8'
);
console.log('Wrote', outPath);
