/**
 * Sanity Schema: enrich.job
 */

export default {
  name: 'enrich.job',
  title: 'Enrichment Job',
  type: 'document',
  fields: [
    { name: 'jobKey', title: 'Job Key', type: 'string' },
    { name: 'jobId', title: 'Job ID', type: 'string' },
    {
      name: 'findingRef',
      title: 'Finding Reference',
      type: 'reference',
      to: [{ type: 'dq.finding' }],
    },
    { name: 'accountKey', title: 'Account Key', type: 'string' },
    { name: 'canonicalUrl', title: 'Canonical URL', type: 'url' },
    { name: 'entityType', title: 'Entity Type', type: 'string' },
    { name: 'entityId', title: 'Entity ID', type: 'string' },
    { name: 'goal', title: 'Goal', type: 'string' },
    { name: 'goalKey', title: 'Goal Key', type: 'string' },
    { name: 'scope', title: 'Scope', type: 'object', fields: [{ name: 'value', type: 'string', title: 'Value', hidden: true }] },
    { name: 'priority', title: 'Priority', type: 'number' },
    { name: 'status', title: 'Status', type: 'string' },
    { name: 'currentStage', title: 'Current Stage', type: 'string' },
    { name: 'completedStages', title: 'Completed Stages', type: 'array', of: [{ type: 'string' }] },
    { name: 'failedStages', title: 'Failed Stages', type: 'array', of: [{ type: 'object', fields: [{ name: 'stage', type: 'string' }, { name: 'error', type: 'text' }, { name: 'timestamp', type: 'datetime' }] }] },
    { name: 'requestedStages', title: 'Requested Stages', type: 'array', of: [{ type: 'string' }] },
    { name: 'includeLinkedIn', title: 'Include LinkedIn', type: 'boolean' },
    { name: 'includeBrief', title: 'Include Brief', type: 'boolean' },
    { name: 'includeVerification', title: 'Include Verification', type: 'boolean' },
    { name: 'maxDepth', title: 'Max Depth', type: 'number' },
    { name: 'budget', title: 'Budget', type: 'number' },
    { name: 'source', title: 'Source', type: 'string' },
    { name: 'createdBy', title: 'Created By', type: 'string' },
    { name: 'attempts', title: 'Attempts', type: 'number' },
    { name: 'maxAttempts', title: 'Max Attempts', type: 'number' },
    { name: 'nextAttemptAt', title: 'Next Attempt At', type: 'datetime' },
    { name: 'leaseExpiresAt', title: 'Lease Expires At', type: 'datetime' },
    { name: 'error', title: 'Error', type: 'string' },
    { name: 'createdAt', title: 'Created At', type: 'datetime' },
    { name: 'updatedAt', title: 'Updated At', type: 'datetime' },
  ],
};
