/**
 * Gmail Draft
 *
 * Stores review-first outreach drafts generated by the worker before they are
 * opened in Gmail compose or sent through the Gmail API.
 */
export default {
  name: 'gmailDraft',
  title: 'Gmail Draft',
  type: 'document',
  fields: [
    { name: 'draftId', title: 'Draft ID', type: 'string' },
    { name: 'actionCandidateId', title: 'Action Candidate ID', type: 'string' },
    { name: 'draftPolicyVersion', title: 'Draft Policy Version', type: 'string' },
    { name: 'strategyVersion', title: 'Strategy Version', type: 'string' },
    {
      name: 'confidenceBreakdown',
      title: 'Confidence Breakdown',
      type: 'object',
      fields: [
        { name: 'dataConfidence', title: 'Data Confidence', type: 'number' },
        { name: 'entityConfidence', title: 'Entity Confidence', type: 'number' },
        { name: 'patternConfidence', title: 'Pattern Confidence', type: 'number' },
        { name: 'actionConfidence', title: 'Action Confidence', type: 'number' },
        { name: 'draftConfidence', title: 'Draft Confidence', type: 'number' },
        { name: 'updatedAt', title: 'Updated At', type: 'datetime' },
      ],
    },
    { name: 'status', title: 'Status', type: 'string' },
    { name: 'accountName', title: 'Account Name', type: 'string' },
    { name: 'recipientName', title: 'Recipient Name', type: 'string' },
    { name: 'recipientTitle', title: 'Recipient Title', type: 'string' },
    { name: 'recipientCompany', title: 'Recipient Company', type: 'string' },
    { name: 'to', title: 'To', type: 'array', of: [{ type: 'string' }] },
    { name: 'cc', title: 'CC', type: 'array', of: [{ type: 'string' }] },
    { name: 'bcc', title: 'BCC', type: 'array', of: [{ type: 'string' }] },
    { name: 'subject', title: 'Subject', type: 'string' },
    { name: 'body', title: 'Body', type: 'text' },
    { name: 'composeUrl', title: 'Compose URL', type: 'url' },
    { name: 'gmailDraftId', title: 'Gmail Draft ID', type: 'string' },
    { name: 'gmailMessageId', title: 'Gmail Message ID', type: 'string' },
    {
      name: 'context',
      title: 'Context',
      type: 'object',
      fields: [{ name: 'value', type: 'text', title: 'Value', hidden: true }],
    },
    { name: 'createdAt', title: 'Created At', type: 'datetime' },
    { name: 'updatedAt', title: 'Updated At', type: 'datetime' },
    { name: 'sentAt', title: 'Sent At', type: 'datetime' },
    { name: 'observedAt', title: 'Observed At', type: 'datetime' },
    { name: 'lastValidatedAt', title: 'Last Validated At', type: 'datetime' },
    { name: 'staleAfter', title: 'Stale After', type: 'datetime' },
    { name: 'refreshPriority', title: 'Refresh Priority', type: 'number' },
    {
      name: 'uncertaintyState',
      title: 'Uncertainty State',
      type: 'string',
      options: { list: ['confirmed', 'likely', 'weakly_inferred', 'contradictory', 'stale', 'needs_validation'] },
    },
  ],
  preview: {
    select: {
      title: 'subject',
      subtitle: 'recipientCompany',
    },
  },
};
