/**
 * Gmail Draft
 *
 * Stores review-first outreach drafts generated by the worker before they are
 * opened in Gmail compose or sent through the Gmail API.
 */
export default {
  name: 'gmailDraft',
  title: 'Gmail Draft',
  type: 'document',
  fields: [
    { name: 'draftId', title: 'Draft ID', type: 'string' },
    { name: 'status', title: 'Status', type: 'string' },
    { name: 'accountName', title: 'Account Name', type: 'string' },
    { name: 'recipientName', title: 'Recipient Name', type: 'string' },
    { name: 'recipientTitle', title: 'Recipient Title', type: 'string' },
    { name: 'recipientCompany', title: 'Recipient Company', type: 'string' },
    { name: 'to', title: 'To', type: 'array', of: [{ type: 'string' }] },
    { name: 'cc', title: 'CC', type: 'array', of: [{ type: 'string' }] },
    { name: 'bcc', title: 'BCC', type: 'array', of: [{ type: 'string' }] },
    { name: 'subject', title: 'Subject', type: 'string' },
    { name: 'body', title: 'Body', type: 'text' },
    { name: 'composeUrl', title: 'Compose URL', type: 'url' },
    { name: 'gmailDraftId', title: 'Gmail Draft ID', type: 'string' },
    { name: 'gmailMessageId', title: 'Gmail Message ID', type: 'string' },
    {
      name: 'context',
      title: 'Context',
      type: 'object',
      fields: [{ name: 'value', type: 'text', title: 'Value', hidden: true }],
    },
    { name: 'createdAt', title: 'Created At', type: 'datetime' },
    { name: 'updatedAt', title: 'Updated At', type: 'datetime' },
    { name: 'sentAt', title: 'Sent At', type: 'datetime' },
  ],
  preview: {
    select: {
      title: 'subject',
      subtitle: 'recipientCompany',
    },
  },
};
